application: status-soap
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: status-soap.application
  
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest